services:
  digitalwallet-web:
    build:
      context: .
      dockerfile: Dockerfile.DigitalWallet.web
    ports:
      - "4222:4200"
    networks:
      - app-network


  nginx:
    image: nginx:stable-alpine
    container_name: SelfResearch_nginx
    ports:
      - "8081:80"
    depends_on:
      - digitalwallet-web
      - usermanagement-webapi
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      
networks:
  app-network:
    driver: bridge